### ISSUE TITLE
Sourcelink broken

### ISSUE THREAD

**Issue by hons82** [clemensg/sqlite3pod#6]
Hi,

the link in the podspec file is not working anymore
`s.source   = { :http => "https://www.sqlite.org/#{Time.now.year}/#{archive_name}.zip" }`
because of the year change. 
Did that happen to you even in the past years?

**Comment by clemensg** [comment]
Hi,

when does this error occur and did you put `pod 'sqlite3'` in your Podfile, as suggested in the README?
Sounds like you are referencing this repo (or its podspec) directly (e.g. by `pod 'sqlite3', podspec: '~/repos/sqlite3pod'`), which is not supported.

By adding `pod 'sqlite3'` to your Podfile, CocoaPods accesses the latest sqlite3.podspec.json file (which was generated from this podspec after I pushed a new version to CocoaPods Trunk), which is currently 3.21.0: https://github.com/CocoaPods/Specs/blob/master/Specs/d/c/2/sqlite3/3.21.0/sqlite3.podspec.json
You can see that this file is static, the year is still 2017 and the link is still working.

The year in the source file (sqlite3.podspec), which I use to push to CocoaPods Trunk, has to be dynamic because when a new version is released, the year in the link is always the current one (for this version).

If you can't get it to work, please post the Podfile you are using.

**Comment by hons82** [comment]
I see... actually I've "copied" your podspec to a private spec repo (because I needed ICU support)
And in the private repo it's not resolved statically so my fault.

Thanks for your help
